### ISSUE TITLE
thank you

### ISSUE THREAD

**Issue by Jimmi08** [oudoken/static_cache#1]
Hello,
at first thank you for this. It really helps. 
In default settings everything works (it just took me a bit time that this is only for quests)

I just have some questions:
Optimize code - it does nothing, doen't it?

Compression - if i set it On, I get blank page. I use xampp, php 7.0, nothing is in logs, I don't know how to test this. Is it because gzip compression is enabled already on server?  

THANKS AGAIN.

**Comment by oudoken** [comment]
Hi,
Yep it's only for non auth users, i've got the idea from similar plugs from wordpress/prestashop.
The key idea is to speed up things for non logged in users so You got: more speed for search engine robots and less resource bleeding from casual users. Well casual users can be a lot of course!

The "optimize code" at this moment does nothing but in future can be an implementation of phpweeme or similar, i need to test a little more on phpweeme cause it give me errors.

The "compression" it's really only here for problem, in the first tests i noticed that on a server with gzip compression the output was compressed (ie binary output on browser) so i've implemented this as a decompress feature... So if You got no problems with the "compression" option disabled You can leave it alone.

Thanks for testing out :) if You have question or ideas share it 👍 
Rob

**Comment by Jimmi08** [comment]
I would be great if I could rid my phpweeme plugin because most of time I don't know what I do. I am Frontend developer, this is out of my league. 

About gzip - isn't there way how to test if gzip is enabled on server?  And then display message or warning or disable this pref?   It's not for me, it's for users that see blank page and will blame your plugin not their settings.

**Comment by oudoken** [comment]
For optimization (phpweeme and the like) it's feasable but in the first place i think e107 need some more polishing on output rules of css / js, that's not a problem of e107 tought cause also in wordpress it's approx the same.
The control over css / js order it's not so easy, not without coding directly.
And plugin that does automagically (says autoptimize on WP) are not steel-proof.

Btw i want to investigate more in this area and maybe something will happen, in terms of seo or engine optimization there's a lot to be done like rich-snippets, better metatagging etc.

Yes the i can test for compression with curl and check if server send a gzipped content, i will look also on this.

Thanks for the suggestion 👍

**Comment by Jimmi08** [comment]
If you dig in code and find where to "catch"  404  pages to be able to save log about them or where to do redirection, you can let me know.  I would like to do it with e_module.php, but I wasn't able to do it. 

https://www.e107.sk/forum/ideas/54/fix-sp-seo-plugin-for-2-or-anything-for-redirect-non-existing-urls/

Thank you.

**Comment by oudoken** [comment]
ok dunno if there's an hook for this... btw if You go into:
e107_handlers/error_page_class.php
You got the function setPageNotFound() just add something like:
    //store temp requested url
    $temp_url = $_SERVER["REDIRECT_URL"];
    $x_log = e107::getLog();
    $x_log->add('404_ERROR_URL', $temp_url, E_LOG_INFORMATIVE, null);
You will get the originating url in the admin log.
Will be a nice addition to the preferences of log: IE loggin urls/request errors.
Thanks 
Rob

**Comment by Jimmi08** [comment]
There is problem that if I set Associate Root namespace to Page - it will go to page.php and method processViewPage() will display page with page error. I created issue about this, waiting for answer. 
But thanks anyway

**Comment by Jimmi08** [comment]
Hi,
just let you know. 

e107 has already inbuild "compression"  css and js. You just need to set Cache JS ON.
