### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Jimmi08** [oudoken/static_cache#2]
Hi,
is needed to load e_module in admin area?

```
if (ADMIN_AREA) {
      return '';
}  
```  
thanks.

**Comment by oudoken** [comment]
Hi @Jimmi08 
Well if You are logged the plugin does not use the cached version, in fact does not produce cache version at all so it's not required, but i will do some tests to check out for problems that may arise.
Thanks for the suggestion!

**Comment by Jimmi08** [comment]
Hm, so why I would asked for something like that?  [ I see it now in code, so it's probably ok. ]

Maybe because it autoloads some stuff what is not needed?  I really can't remember.  But again thank for great plugin.

**Comment by oudoken** [comment]
Hi @Jimmi08 
I mean we can add but it's not required
The "old" (0.8) ways was 
```
if(e_ADMIN_AREA !==true)
...
}
```
But i can't find how this can be converted to V2 code, maybe better to ask Cameron or some other of the e107 team.
Btw because when You visit the admin area You are logged, the plugin will present always the "fresh" page and no static content is generated.
Thanks Kind Regards
Rob

**Comment by Jimmi08** [comment]
I wrote it to you above.  It's ADMIN_AREA now.  But maybe old way works too, I wasn't here in 0.8 times.

It's about saving sources, not displaying fresh version.
Admin is already slow. 

It was just notice, you don't need to change it.

Thanks

**Comment by oudoken** [comment]
Hi @Jimmi08 
I see in :
https://github.com/e107inc/e107/blob/master/e107_handlers/e107_class.php

A lot of reference to e_ADMIN_AREA and ONE to ADMIN_AREA, maybe it's the new name but it's NOT defined...

Emitting via log:
$x_log = e107::getLog();
$x_log->add('is admin area??', 'ADMIN_AREA: '.ADMIN_AREA.' | e_ADMIN_AREA: '.e_ADMIN_AREA, E_LOG_INFORMATIVE, '999');

Lead to:
(LOGGED USER)
Administrator | 999 | is admin area?? | ADMIN_AREA: ADMIN_AREA \| e_ADMIN_AREA: 1

(NON LOGGED USER)
Anonimo	999	is admin area??	ADMIN_AREA: ADMIN_AREA | e_ADMIN_AREA:

So ADMIN_AREA seems NOT defined

I think You have found a bug... I will wrote to team in e107 Github

Thanks Bye
Rob

**Comment by oudoken** [comment]
https://github.com/e107inc/e107/issues/3465

**Comment by rica-carv** [comment]
You can troubleshoot if e_ADMIN_AREA and / or ADMIN_AREA is defined...
A simple `print_r` in the code will troubleshoot them....

**Comment by oudoken** [comment]
Hi @rica-carv 
Yep the output is on the log via:
$x_log = e107::getLog();
$x_log->add('is admin area??', 'ADMIN_AREA: '.ADMIN_AREA.' | e_ADMIN_AREA: '.e_ADMIN_AREA, E_LOG_INFORMATIVE, '999');

ADMIN_AREA seems not defined in 
https://github.com/e107inc/e107/blob/master/e107_handlers/e107_class.php

**Comment by oudoken** [comment]
Added check in V 1.0.5
