### ISSUE TITLE
question from curiosity

### ISSUE THREAD

**Issue by Jimmi08** [oudoken/static_cache#3]
I still didn't get fully how this works (mainly that phpfastcache part), but I saw it saves html files in very weird folder structure. 
Important that it works. 

I consider next plugin where I would like to save page to html (one html file) and load its cached version. Just idea for AMP pages.

**Comment by oudoken** [comment]
Hi @Jimmi08 
Yep the purpose is to save a static version of the requested page via phpFastCache.
Then when another (NOT LOGGED IN) user request the same page the saved static page will be presented to the user, so the server respond in really fast times, even shared hosting.
So when You have a site with big load or Your hosting is low on resources the plugin help.
Also the search engine will hit pages at an higher speed resulting in higher scores.
The folder structure can be altered and also the file name of static file created.
The ST_CACHE_EXPIRATION const (You can set in admin area) does set the time for the url to be regenerated.

**Comment by Jimmi08** [comment]
Thanks
