### ISSUE TITLE
Cache Full Path

### ISSUE THREAD

**Issue by mostym** [oudoken/static_cache#4]
The cache full path field shows ST_CACHE_SAVE_PATH

![image](https://user-images.githubusercontent.com/25377269/51831502-1ba21280-22a7-11e9-88ce-9e7a35189c56.png)

PS.  I freaking love you for making this plugin :D

**Comment by oudoken** [comment]
Seems a problem with def not setting value, i wll check it out.

**Comment by oudoken** [comment]
now is working in repo
