### ISSUE TITLE
Request:  Add ability to change cacheFileExtension from plugin page

### ISSUE THREAD

**Issue by mostym** [oudoken/static_cache#6]
Hey there.  I would love the ability to change the cacheFileExtension from the plugin admin page.

Thanks!

**Comment by oudoken** [comment]
Added on 1.1.0 release.
Btw because of security only some extensions are avaible see also this ticket on phpFastCache:
 https://github.com/PHPSocialNetwork/phpfastcache/issues/467
Thanks for the suggestion!

**Comment by mostym** [comment]
Hey there.  I kinda wanted the ability to have .html as well :D

**Comment by oudoken** [comment]
Hi, the problem is the folder where the files are created is writable so this may lead to code injection inside files... Html could be a potential target.
It's feasable but need to modify code from phpFastCache i will ask developers but for now we must stay with the extensions allowed from phpFastCache.
Thanks!

**Comment by mostym** [comment]
The problem is that, i'm using cloudflare as a CDN and they don't allow me to cache .txt files, only html files.

**Comment by oudoken** [comment]
Hi mostym, ok i see. The key problem here is that the folder containing the static cache must not be accessible DIRECTLY for security reason.
In this case would be better configure CF with page rules, i'm pretty sure this is doable on CF:
https://support.cloudflare.com/hc/en-us/articles/200172826-Can-dynamic-sites-work-with-Cloudflare-
https://blog.cloudflare.com/introducing-pagerules-advanced-caching/
But i'm not an expert on CF (i use it btw).
