### ISSUE TITLE
I can't load the static_cache Cache files list

### ISSUE THREAD

**Issue by mostym** [oudoken/static_cache#9]
I have around 105,000 cached files and when I go to the admin area and click on the  Cache files list, There's no content displayed

![image](https://user-images.githubusercontent.com/25377269/52032006-f47c5880-24d3-11e9-9935-41267f83f404.png)

**Comment by mostym** [comment]
Ok, so this appears to be a php issue.

```
2019/01/30 21:25:55 [error] 2059#2059: *57570 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 43213712 bytes) in /var/www/mydomain.com/e107_plugins/static_cache/admin_config.php on line 414" while reading response header from upstream, client: 76.171.67.52, server: www.mydomain.com, request: "GET /plugins/static_cache/admin_config.php?mode=sc_cached&action=custom HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "www.mydomain.com", referrer: "https://www.mydomain.com/plugins/static_cache/admin_config.php"
```

Though, I'm assuming, that the Cache files list tries and loads the entire list of cached files from the db and php just runs out of memory.  Is there a way to only load 100 records at a time instead of the entire cache list?

**Comment by oudoken** [comment]
Yep the list must work in ajax...
Btw at this time is loading the whole list from db.
So bug / enhancement.
Will add soon
Thanks

**Comment by oudoken** [comment]
Ajax list has been added on version 1.1.0
Thanks for pointing this out!
